/**
 * Task endpoints. PROJECT-SPEC.md §6.4, §6.5, §7.3.
 *
 *   POST   /api/tasks       create
 *   PATCH  /api/tasks/:id   edit any field, complete/un-complete, move, reorder
 *   DELETE /api/tasks/:id   permanent
 *
 * Two rules shape this module:
 *
 * **Completion is server-clocked.** The client sends `completed: true|false`
 * and never a timestamp; the server writes `Date.now()` or `NULL`. A client
 * clock that is wrong or adversarial cannot land a completion in the past.
 *
 * **Positions come from the client.** Creating, reordering, moving between
 * boards, and un-completing all carry a position generated by
 * `shared/order.ts`. Un-completing carries the end of the active list, because
 * §7.3 says a restored task does not go back where it was.
 */

import type { ColumnPatch, Env } from '../db';
import {
  deleteTask,
  insertTask,
  selectBoard,
  selectTask,
  replaceDependencies,
  selectTasksOfBoard,
  updateTask,
} from '../db';
import { apiError, json, noContent } from '../http';
import { canDependOn, lookupOf } from '../../shared/dependencies';
import type { Task } from '../../shared/types';
import {
  MAX_TASK_NAME,
  absent,
  assertBlockWithinDay,
  assertTimeHasDate,
  boolean,
  jsonBody,
  nullableDifficulty,
  nullableDueDate,
  nullableDueTime,
  nullableDurationMinutes,
  nullableScheduledAt,
  nullableText,
  dependsOnList,
  requiredId,
  requiredName,
  requiredPosition,
} from '../validate';

/**
 * Whether every id in `dependsOn` is a legal prerequisite for a task that will
 * look like `resulting` once the write lands.
 *
 * The check runs against the *resulting* state rather than the stored one,
 * which matters when a single PATCH both moves a task and sets its
 * dependencies: the board they are validated against has to be the board it is
 * going to.
 *
 * **The links are checked one at a time, each against the set accepted so far.**
 * A set validated all-at-once could smuggle a cycle past the check — two links
 * that are individually fine can close a loop together — so the working copy
 * grows a link at a time and each new one is tested against a task that already
 * carries its predecessors. That is also exactly the order the user added them
 * in, so the link a refusal is about is the one they just chose.
 *
 * `canDependOn` is the same function the composer builds its options from, so
 * the client cannot offer something the server would then refuse.
 */
async function illegalDependency(
  env: Env,
  resulting: Task,
  dependsOn: readonly string[],
): Promise<string | null> {
  if (dependsOn.length === 0) return null;

  const siblings = await selectTasksOfBoard(env.DB, resulting.boardId);
  const others = siblings.filter((sibling) => sibling.id !== resulting.id);

  let working: Task = { ...resulting, dependsOn: [] };
  for (const id of dependsOn) {
    const prerequisite = others.find((sibling) => sibling.id === id);
    if (!prerequisite) return id;

    // The lookup carries the working copy rather than the stored task, so a
    // cycle search that comes back around sees the links being proposed.
    if (!canDependOn(working, prerequisite, lookupOf([...others, working]))) return id;
    working = { ...working, dependsOn: [...working.dependsOn, id] };
  }

  return null;
}

async function create(request: Request, env: Env): Promise<Response> {
  const body = await jsonBody(request);

  const boardId = requiredId(body.boardId, 'boardId');
  const dueDate = absent(body, 'dueDate') ? null : nullableDueDate(body.dueDate);
  const dueTime = absent(body, 'dueTime') ? null : nullableDueTime(body.dueTime);
  assertTimeHasDate(dueDate, dueTime);

  const durationMinutes = absent(body, 'durationMinutes')
    ? null
    : nullableDurationMinutes(body.durationMinutes);
  const scheduledAt = absent(body, 'scheduledAt') ? null : nullableScheduledAt(body.scheduledAt);
  assertBlockWithinDay({ durationMinutes, scheduledAt });

  const draft = {
    boardId,
    name: requiredName(body.name, MAX_TASK_NAME, 'name'),
    notes: absent(body, 'notes') ? null : nullableText(body.notes, 'notes'),
    dueDate,
    dueTime,
    durationMinutes,
    scheduledAt,
    difficulty: absent(body, 'difficulty') ? null : nullableDifficulty(body.difficulty),
    priority: absent(body, 'priority') ? false : boolean(body.priority, 'priority'),
    blocked: absent(body, 'blocked') ? false : boolean(body.blocked, 'blocked'),
    // The id is minted by the insert, so there is nothing yet for a self-link
    // to point at; the empty string is a placeholder no task can match.
    dependsOn: dependsOnList(body.dependsOn, ''),
    position: requiredPosition(body.position),
  };

  // Checked before the insert so an unknown board is a 404 rather than a
  // foreign-key failure surfacing as a 500.
  if (!(await selectBoard(env.DB, boardId))) return apiError('board not found', 404);

  if (draft.dependsOn.length > 0) {
    // A task being created cannot be the target of a cycle — nothing depends on
    // it yet — so this is only "do they exist, and are they on this board".
    const siblings = await selectTasksOfBoard(env.DB, boardId);
    const known = new Set(siblings.map((sibling) => sibling.id));
    if (draft.dependsOn.some((entry) => !known.has(entry))) {
      return apiError('dependsOn must be other tasks on the same board', 400);
    }
  }

  const task = await insertTask(env.DB, draft);
  // The edges live in their own table, so they are their own write. The task
  // returned carries them, because the client applies this response over its
  // optimistic copy and a response with no links would erase them on screen.
  if (draft.dependsOn.length > 0) {
    await replaceDependencies(env.DB, task.id, draft.dependsOn);
  }
  return json({ ...task, dependsOn: draft.dependsOn }, { status: 201 });
}

async function patch(request: Request, env: Env, id: string): Promise<Response> {
  const body = await jsonBody(request);

  const existing = await selectTask(env.DB, id);
  if (!existing) return apiError('task not found', 404);

  const columns: ColumnPatch = {};

  if (!absent(body, 'name')) columns.name = requiredName(body.name, MAX_TASK_NAME, 'name');
  if (!absent(body, 'notes')) columns.notes = nullableText(body.notes, 'notes');
  if (!absent(body, 'difficulty')) columns.difficulty = nullableDifficulty(body.difficulty);
  if (!absent(body, 'priority')) columns.priority = boolean(body.priority, 'priority') ? 1 : 0;
  if (!absent(body, 'blocked')) columns.blocked = boolean(body.blocked, 'blocked') ? 1 : 0;
  if (!absent(body, 'position')) columns.position = requiredPosition(body.position);

  // The block is validated against the task's *resulting* state, for the same
  // reason the date/time pair below is: a patch that only lengthens an
  // already-late block pushes it past midnight, and the patch alone cannot see
  // that. An unsnapped start and an over-long duration are refused outright —
  // never rounded — so the row the client drew and the row the server stores
  // are the same row.
  const durationMinutes = absent(body, 'durationMinutes')
    ? existing.durationMinutes
    : nullableDurationMinutes(body.durationMinutes);
  const scheduledAt = absent(body, 'scheduledAt')
    ? existing.scheduledAt
    : nullableScheduledAt(body.scheduledAt);
  assertBlockWithinDay({ durationMinutes, scheduledAt });
  if (!absent(body, 'durationMinutes')) columns.duration_minutes = durationMinutes;
  if (!absent(body, 'scheduledAt')) columns.scheduled_at = scheduledAt;

  // The date/time pair is validated against the task's *resulting* state, so
  // clearing the date while leaving an old time behind is caught as well.
  const dueDate = absent(body, 'dueDate') ? existing.dueDate : nullableDueDate(body.dueDate);
  const dueTime = absent(body, 'dueTime') ? existing.dueTime : nullableDueTime(body.dueTime);
  assertTimeHasDate(dueDate, dueTime);
  if (!absent(body, 'dueDate')) columns.due_date = dueDate;
  if (!absent(body, 'dueTime')) columns.due_time = dueTime;

  let boardId = existing.boardId;
  if (!absent(body, 'boardId')) {
    boardId = requiredId(body.boardId, 'boardId');
    if (boardId !== existing.boardId && !(await selectBoard(env.DB, boardId))) {
      return apiError('board not found', 404);
    }
    columns.board_id = boardId;
  }

  // A dependency only means anything within one board, so moving a task off its
  // board drops every link rather than leaving gates pointing somewhere the
  // user can no longer see. An explicit `dependsOn` in the same request still
  // wins — that is a move and a re-link, and it is validated against the
  // destination board.
  let dependsOn = existing.dependsOn;
  let dependenciesChanged = false;
  if (!absent(body, 'dependsOn')) {
    dependsOn = dependsOnList(body.dependsOn, id);
    dependenciesChanged = true;
  } else if (boardId !== existing.boardId && dependsOn.length > 0) {
    dependsOn = [];
    dependenciesChanged = true;
  }

  if (dependenciesChanged) {
    const offender = await illegalDependency(env, { ...existing, boardId, dependsOn }, dependsOn);
    if (offender !== null) {
      return apiError(
        'dependsOn must be other tasks on the same board, and cannot form a cycle',
        400,
      );
    }
  }

  if (!absent(body, 'completed')) {
    const completing = boolean(body.completed, 'completed');
    // The gate, enforced where it cannot be skipped. The client disables the
    // checkbox for a gated task; this is what makes the rule true rather than
    // merely presented.
    // *Any* outstanding prerequisite refuses the completion, not just the
    // first — which is the whole meaning of a set of them.
    if (completing && dependsOn.length > 0) {
      const siblings = await selectTasksOfBoard(env.DB, boardId);
      const outstanding = siblings.some(
        (sibling) => dependsOn.includes(sibling.id) && sibling.completedAt === null,
      );
      if (outstanding) return apiError('this task is waiting on another task', 409);
    }
    columns.completed_at = completing ? Date.now() : null;
  }

  if (dependenciesChanged) await replaceDependencies(env.DB, id, dependsOn);

  // A patch that only changed links has no columns to write, but the caller
  // still needs the task back with its new set.
  if (Object.keys(columns).length === 0) return json({ ...existing, dependsOn });

  const task = await updateTask(env.DB, id, columns);
  return task ? json({ ...task, dependsOn }) : apiError('task not found', 404);
}

async function destroy(env: Env, id: string): Promise<Response> {
  const deleted = await deleteTask(env.DB, id);
  return deleted ? noContent() : apiError('task not found', 404);
}

/** Returns null when the path is not a task path, so the router falls through. */
export function handleTasks(request: Request, env: Env, pathname: string): Promise<Response> | null {
  if (pathname === '/api/tasks') {
    if (request.method !== 'POST') return Promise.resolve(apiError('Method not allowed', 405));
    return create(request, env);
  }

  const match = /^\/api\/tasks\/([^/]+)$/.exec(pathname);
  if (!match) return null;

  const id = decodeURIComponent(match[1]);
  if (request.method === 'PATCH') return patch(request, env, id);
  if (request.method === 'DELETE') return destroy(env, id);
  return Promise.resolve(apiError('Method not allowed', 405));
}
