/**
 * Task endpoints. PROJECT-SPEC.md §6.4, §6.5, §7.3.
 *
 *   POST   /api/tasks       create
 *   PATCH  /api/tasks/:id   edit any field, complete/un-complete, move, reorder
 *   DELETE /api/tasks/:id   permanent
 *
 * Two rules shape this module:
 *
 * **Completion is server-clocked.** The client sends `completed: true|false`
 * and never a timestamp; the server writes `Date.now()` or `NULL`. A client
 * clock that is wrong or adversarial cannot land a completion in the past.
 *
 * **Positions come from the client.** Creating, reordering, moving between
 * boards, and un-completing all carry a position generated by
 * `shared/order.ts`. Un-completing carries the end of the active list, because
 * §7.3 says a restored task does not go back where it was.
 */

import type { ColumnPatch, Env } from '../db';
import { deleteTask, insertTask, selectBoard, selectTask, updateTask } from '../db';
import { apiError, json, noContent } from '../http';
import {
  MAX_TASK_NAME,
  absent,
  assertTimeHasDate,
  boolean,
  jsonBody,
  nullableDifficulty,
  nullableDueDate,
  nullableDueTime,
  nullableDuration,
  nullableText,
  requiredId,
  requiredName,
  requiredPosition,
} from '../validate';

async function create(request: Request, env: Env): Promise<Response> {
  const body = await jsonBody(request);

  const boardId = requiredId(body.boardId, 'boardId');
  const dueDate = absent(body, 'dueDate') ? null : nullableDueDate(body.dueDate);
  const dueTime = absent(body, 'dueTime') ? null : nullableDueTime(body.dueTime);
  assertTimeHasDate(dueDate, dueTime);

  const draft = {
    boardId,
    name: requiredName(body.name, MAX_TASK_NAME, 'name'),
    notes: absent(body, 'notes') ? null : nullableText(body.notes, 'notes'),
    dueDate,
    dueTime,
    duration: absent(body, 'duration') ? null : nullableDuration(body.duration),
    difficulty: absent(body, 'difficulty') ? null : nullableDifficulty(body.difficulty),
    priority: absent(body, 'priority') ? false : boolean(body.priority, 'priority'),
    blocked: absent(body, 'blocked') ? false : boolean(body.blocked, 'blocked'),
    position: requiredPosition(body.position),
  };

  // Checked before the insert so an unknown board is a 404 rather than a
  // foreign-key failure surfacing as a 500.
  if (!(await selectBoard(env.DB, boardId))) return apiError('board not found', 404);

  return json(await insertTask(env.DB, draft), { status: 201 });
}

async function patch(request: Request, env: Env, id: string): Promise<Response> {
  const body = await jsonBody(request);

  const existing = await selectTask(env.DB, id);
  if (!existing) return apiError('task not found', 404);

  const columns: ColumnPatch = {};

  if (!absent(body, 'name')) columns.name = requiredName(body.name, MAX_TASK_NAME, 'name');
  if (!absent(body, 'notes')) columns.notes = nullableText(body.notes, 'notes');
  if (!absent(body, 'duration')) columns.duration = nullableDuration(body.duration);
  if (!absent(body, 'difficulty')) columns.difficulty = nullableDifficulty(body.difficulty);
  if (!absent(body, 'priority')) columns.priority = boolean(body.priority, 'priority') ? 1 : 0;
  if (!absent(body, 'blocked')) columns.blocked = boolean(body.blocked, 'blocked') ? 1 : 0;
  if (!absent(body, 'position')) columns.position = requiredPosition(body.position);

  // The date/time pair is validated against the task's *resulting* state, so
  // clearing the date while leaving an old time behind is caught as well.
  const dueDate = absent(body, 'dueDate') ? existing.dueDate : nullableDueDate(body.dueDate);
  const dueTime = absent(body, 'dueTime') ? existing.dueTime : nullableDueTime(body.dueTime);
  assertTimeHasDate(dueDate, dueTime);
  if (!absent(body, 'dueDate')) columns.due_date = dueDate;
  if (!absent(body, 'dueTime')) columns.due_time = dueTime;

  if (!absent(body, 'completed')) {
    columns.completed_at = boolean(body.completed, 'completed') ? Date.now() : null;
  }

  if (!absent(body, 'boardId')) {
    const boardId = requiredId(body.boardId, 'boardId');
    if (boardId !== existing.boardId && !(await selectBoard(env.DB, boardId))) {
      return apiError('board not found', 404);
    }
    columns.board_id = boardId;
  }

  if (Object.keys(columns).length === 0) return json(existing);

  const task = await updateTask(env.DB, id, columns);
  return task ? json(task) : apiError('task not found', 404);
}

async function destroy(env: Env, id: string): Promise<Response> {
  const deleted = await deleteTask(env.DB, id);
  return deleted ? noContent() : apiError('task not found', 404);
}

/** Returns null when the path is not a task path, so the router falls through. */
export function handleTasks(request: Request, env: Env, pathname: string): Promise<Response> | null {
  if (pathname === '/api/tasks') {
    if (request.method !== 'POST') return Promise.resolve(apiError('Method not allowed', 405));
    return create(request, env);
  }

  const match = /^\/api\/tasks\/([^/]+)$/.exec(pathname);
  if (!match) return null;

  const id = decodeURIComponent(match[1]);
  if (request.method === 'PATCH') return patch(request, env, id);
  if (request.method === 'DELETE') return destroy(env, id);
  return Promise.resolve(apiError('Method not allowed', 405));
}
